### ISSUE TITLE
Unkown message: Confirm(Offsets(...))

### ISSUE THREAD

**Issue by kufi** [cakesolutions/scala-kafka-client#51]
Sometimes (especially on startup) we get the following message in our logs:

    Unknown message: Confirm(Offsets(... = 550, ... = 8),true)

This leads to messages being processed multiple times in the system, sometimes up to 20-30 times, until the actor suddenly gets into a valid state and starts to process the Confirm-messages correctly.

Is there a way to prevent this problem? After looking through the code there seems to be a problem when a Confirm-message is processed in the "ready"-state, despite that state having a comment that no unconfirmed messages should be present.

**Comment by jkpl** [comment]
Hi! Thanks for reporting this problem. What version of scala-kafka-client are you using? We'll look into the problem as soon as we can.

**Comment by jkpl** [comment]
Hi, we've released versions `0.9.0.0-RC1` (compatible with Kafka 0.9) and `0.10.0.0-RC1` (compatible with Kafka 0.10). Can you try if you have the same problem with either of these drivers?

**Comment by kufi** [comment]
Ok, I'll try it and report back as soon as possible. At the moment we're using 0.7.0.

**Comment by kufi** [comment]
Ok, I've found the problem. It only happens when we use an unconfirmedTimeout (is activated normally). This leads to a redelivery of the same message, which we then confirm twice, thus leading to two Confirm messages in the queue right behind each other.

This can lead to infinite loops, where the same bunch of messages are sent endlessly, because the subscriber gets unexpected confirms for offsets.

Disabling the unconfirmedTimeout functionality got rid of the problem.

**Comment by jkpl** [comment]
Thanks for taking the time to investigate the problem!

If you want to use the `unconfirmedTimeout` feature, you could also try deduplicating the redeliveries by comparing the received offsets with previously received offsets. However, if you're confident that the actor receiving the batches from consumer actor will not lose the batches, disabling the `unconfirmedTimeout` is definitely a valid option.

I added explicit message handling for unexpected confirmations, so that the messages don't end up in the dead letter queue. This change will be included in the next release.

We'll also tune the default value of `unconfirmedTimeout` and make the feature more visible to the client user. I'm not completely sure what it will look like in the end, but I got something planned for it. It would be good to get some feedback on how to make the user experience better.
