### ISSUE TITLE
following processing steps after consuming event from kafka

### ISSUE THREAD

**Issue by mazorigal** [cakesolutions/scala-kafka-client#53]
HI,

it is not an issue, more a question, but didnt find any other place where to ask it.

in my use case, I am fetching events from kafka and would like to enrich the event using some kind of API (lets assume REST API), then persist the event in cassandra, and finally to send the event to other kafka topic.

How would be better to implement it, tacking into account the order of events must be preserved ?

1 - Should each step (enrich, persist, kakfa producer) be done in dedicated actor ?

2 - Should all be done in the same Actor (akka reactive streams, for example, try to do as many steps as possible in same actor) ?

3 - another idea that I have is to use akka reactive stream and hence to extend the receiving actor
(SampleAcceptorActor in the example from here:
http://www.cakesolutions.net/teamblogs/getting-started-with-kafka-using-scala-kafka-client-and-akka)
with ActorPublisher so that the receiving actor will be kind of reactive source for the following process steps, which will executed using the akka reactive stream api ?

small update,
I have decide to try option 3.
this is my code based on example from akka reactive streams docs:

```
class ConsumerAtMostOnceReactiveActor(config: Config, clientID: String, maxBufferSize: Int, topics: List[String]) extends ActorPublisher[ConsumerRecord[String, String]] with ActorLogging {

  import akka.stream.actor.ActorPublisherMessage._

  private val extractor = ConsumerRecords.extractor[String, String]

  val MaxBufferSize = maxBufferSize
  var buf = Vector.empty[ConsumerRecord[String, String]]

  // Configuration specific to the Async Consumer Actor
  val actorConf = KafkaConsumerActor.Conf(topics, 1.seconds, 3.seconds)

  private val kafkaConsumerActor = context.actorOf(
    KafkaConsumerActor.props(
      consumerConf = KafkaConsumer.Conf(
        config.withValue("client.id", ConfigValueFactory.fromAnyRef(clientID)),
        keyDeserializer = new StringDeserializer,
        valueDeserializer = new StringDeserializer
      ),
      actorConf = actorConf,
      self
    ),
    "KafkaConsumer"
  )

  override def preStart() = {
    super.preStart()
    kafkaConsumerActor ! Subscribe()
  }

  override def postStop() = {
    kafkaConsumerActor ! Unsubscribe
    Logger.root.info("shutting down kafka consumer system")
    super.postStop()
  }

  override def receive = {
    case extractor(consumerRecords) if buf.size == MaxBufferSize =>
    case extractor(consumerRecords) =>
      kafkaConsumerActor ! Confirm(consumerRecords.offsets, commit = true)
      buf ++= consumerRecords.recordsList
      deliverBuf()
    case Request(_) =>
      deliverBuf()
    case Cancel =>
      context.stop(self)
  }

  @tailrec final def deliverBuf(): Unit =
    if (totalDemand > 0) {
      /*
       * totalDemand is a Long and could be larger than
       * what buf.splitAt can accept
       */
      if (totalDemand <= Int.MaxValue) {
        val (use, keep) = buf.splitAt(totalDemand.toInt)
        buf = keep
        use foreach onNext
      } else {
        val (use, keep) = buf.splitAt(Int.MaxValue)
        buf = keep
        use foreach onNext
        deliverBuf()
      }
    }
}
```

IT would be still great to get feedback regarding my question (which option will be better, and as well regarding my way of implementing option 3)

Thanks,

**Comment by jkpl** [comment]
Hi,

I've found the layout of the actors to vary quite a lot between different kinds of problems. Sometimes it's useful to have multiple actors in the processing pipeline, and sometimes I only use one actor for processing data with the help of asynchronous computations (e.g. Scala Futures). I don't have clear guidelines on what's the most suitable actor layout for your use-case, but here are some things you might want to consider.

### Delivery guarantees

What delivery guarantees are necessary? When can your processing actor consider the computation to be processed far enough that it can safely send a confirmation back to the consumer actor? If you need at least once delivery through the whole pipeline, you can achieve that by sending the confirmation after all of your tasks in the processing pipeline have been finished.

### Pipelining work

Since you have multiple IO actions (REST calls, Cassandra writes) happening in your Kafka message processor, you might want to think about how you're going to efficiently pipeline the work for the incoming data with the ordering of results in mind.

The Kafka consumer actor will always send data in batches, and it will only supply the next batch once the previous batch has been confirmed. This is done because it can be very tricky to keep offset commit positions consistent if multiple batches are processed concurrently. It also means that pipelining has to happen inside one batch instead of between batches. Here are some options you might want to try:

* Parallelise tasks that are not ordering sensitive. For example, if the REST API you mentioned is stateless, the calls to that API can be run in parallel to each other. You can then synchronise the results, if you need the call results to be back in order.
* Add Kafka topics between IO tasks. This will allow parallelising work between different sequential IO tasks. The downside is that it creates additional hops between the application and Kafka.

### Akka streams

I don't have much experience in dealing with Akka streams, so I can't comment much on that. However, if you're planning on using it, you might want to check out [Reactive Kafka](https://github.com/akka/reactive-kafka), which provides Kafka bindings for Akka streams.
