### ISSUE TITLE
at most once

### ISSUE THREAD

**Issue by mazorigal** [cakesolutions/scala-kafka-client#54]
Hi,

Is there a way to use at most once commit strategy, but to commit each record separately instead in batches ?

Thanks,

**Comment by jkpl** [comment]
Currently we only support the ability to commit by batch. When you commit a batch you receive the next batch.

Note that Kafka also only supports [committing records by offsets](http://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#commitSync(java.util.Map)) instead of individual records, so scala-kafka-client will always have that same limitation. Technically we could allow committing offsets partially, but that requires calculating the offsets manually in the user code, which might me more trouble than worth.

If the batches in your case are too large to be committed in one commit, I recommend tuning maximum size of consumed batches to be smaller. See [Kafka documentation on consumer configuration](http://kafka.apache.org/documentation.html#newconsumerconfigs) for `max.poll.records` and `max.partition.fetch.bytes`.

**Comment by mazorigal** [comment]
Thanks for the answer,

regarding the offset and unconfirmed.timeout, how would be the behaviour if from time to time (lets say 1 out 1000 cases) the commit is done after the timeout ?
I guess that after the timeout same batch will be send again to the receiving actor, so it will probably process it again ?

**Comment by jkpl** [comment]
If the timeout is triggered before the consumer actor receives a confirmation, the batch will be redelivered to the receiving actor. How the batch is processed then depends on the receiving actor. You can add your own redelivery detection to the receiving actor (e.g. compare the offsets of the received batch to the previously known offsets), if necessary. If you don't need the redeliveries at all, you can disable them by setting `unconfirmed.timeout` to `0`.

**Comment by mazorigal** [comment]
btw, what other config params of the consumer actor I can tune except the unconfirmed.timeout and poll intervals ?
Can I for example configure the buffer size of the consumer actor?
in which case the buffer can be full ?
What will be the behaviour of the consumer actor in case the buffer is full ?

**Comment by jkpl** [comment]
Unconfirmed timeout, poll interval, and the Kafka consumer configurations are the only configurations you can tune for now.

The consumer actor will only buffer one batch so that it can immediately send a batch to the receiver actor after confirmation. However, you can tune the size of the batches as mentioned earlier.

When the consumer actor buffer is full (one batch unconfirmed, one batch buffered), no new messages are fetched from Kafka until the previously sent batch has been confirmed. When the actor receives a confirmation, the buffered batch is sent to the receiver actor, and the actor starts fetching the next batch from Kafka to fill its buffer.
